apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name kafka-go
  namespace: kafka
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      name: *name
  template:
    metadata:
      labels:
        name: *name
    spec:
      containers:
        - name: *name
          image: chechiachang/kafka-go:latest
          env:
            - name: KAFKA_TOPIC
              value: "kafka-go-ticker"
            - name: KAFKA_PARTITION
              value: "0"
            - name: KAFKA_URL
              value: "kafka-1-kafka-bootstrap:9092"
          #livenessProbe:
          #  httpGet:
          #    path: /healthy
          #    port: http
          #  initialDelaySeconds: 10
          #  periodSeconds: 30
          #readinessProbe:
          #  httpGet:
          #    path: /ready
          #    port: http
          #  initialDelaySeconds: 10
          #  periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 10m
              memory: 100Mi
  strategy:
    type: Recreate
