apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name kafka-stress-test
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      name: *name
  template:
    metadata:
      labels:
        name: *name
    spec:
      containers:
        - name: *name
          image: confluentinc/cp-kafka:5.5.0
          env:
            - name: KAFKA_URL
              value: "kafka-3-kafka-bootstrap:9092"
          resources:
            limits:
              cpu: 1000m
              memory: 3000Mi
            requests:
              cpu: 10m
              memory: 100Mi
          command: ["sleep"]
          args: ["36000"]
  strategy:
    type: Recreate
